import json

errors = json.loads(r'''[{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Object of class `NoneType` has no attribute `_read_ref`",
	"source": "Pyre2",
	"startLineNumber": 1498,
	"startColumn": 16,
	"endLineNumber": 1498,
	"endColumn": 28,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Object of class `NoneType` has no attribute `_read_ref`",
	"source": "Pyre2",
	"startLineNumber": 1539,
	"startColumn": 27,
	"endLineNumber": 1539,
	"endColumn": 45,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Object of class `NoneType` has no attribute `_commute_ref`",
	"source": "Pyre2",
	"startLineNumber": 1561,
	"startColumn": 29,
	"endLineNumber": 1561,
	"endColumn": 68,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "no-matching-overload",
	"severity": 8,
	"message": "Cannot index into `list[tuple[VersionStamp, Unknown]]`\n  No matching overload found for function `list.__getitem__`, reporting errors for closest overload: `(SupportsIndex) -> tuple[VersionStamp, Unknown]`",
	"source": "Pyre2",
	"startLineNumber": 1603,
	"startColumn": 25,
	"endLineNumber": 1603,
	"endColumn": 47,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `slice[int, int, int]` is not assignable to parameter with type `SupportsIndex` in function `list.__getitem__`",
	"source": "Pyre2",
	"startLineNumber": 1603,
	"startColumn": 39,
	"endLineNumber": 1603,
	"endColumn": 46,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "not-callable",
	"severity": 8,
	"message": "Expected a callable, got None",
	"source": "Pyre2",
	"startLineNumber": 1672,
	"startColumn": 36,
	"endLineNumber": 1672,
	"endColumn": 51,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Function declared to return `?_TypeVar`, but one or more paths are missing an explicit `return`",
	"source": "Pyre2",
	"startLineNumber": 1680,
	"startColumn": 62,
	"endLineNumber": 1680,
	"endColumn": 63,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "not-callable",
	"severity": 8,
	"message": "Expected a callable, got None",
	"source": "Pyre2",
	"startLineNumber": 1702,
	"startColumn": 40,
	"endLineNumber": 1702,
	"endColumn": 55,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "not-callable",
	"severity": 8,
	"message": "Expected a callable, got None",
	"source": "Pyre2",
	"startLineNumber": 1718,
	"startColumn": 36,
	"endLineNumber": 1718,
	"endColumn": 51,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "no-matching-overload",
	"severity": 8,
	"message": "Cannot index into `tuple[Unknown, ...]`\n  No matching overload found for function `tuple.__getitem__`, reporting errors for closest overload: `(SupportsIndex) -> Unknown`",
	"source": "Pyre2",
	"startLineNumber": 1847,
	"startColumn": 33,
	"endLineNumber": 1847,
	"endColumn": 49,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `slice[int, int, int]` is not assignable to parameter with type `SupportsIndex` in function `tuple.__getitem__`",
	"source": "Pyre2",
	"startLineNumber": 1847,
	"startColumn": 45,
	"endLineNumber": 1847,
	"endColumn": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Generic attribute `empty` of class `PersistentVector` is not visible on the class",
	"source": "Pyre2",
	"startLineNumber": 1852,
	"startColumn": 20,
	"endLineNumber": 1852,
	"endColumn": 42,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "no-matching-overload",
	"severity": 8,
	"message": "Cannot index into `tuple[Unknown, ...]`\n  No matching overload found for function `tuple.__getitem__`, reporting errors for closest overload: `(SupportsIndex) -> Unknown`",
	"source": "Pyre2",
	"startLineNumber": 1853,
	"startColumn": 33,
	"endLineNumber": 1853,
	"endColumn": 48,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `slice[int, int, int]` is not assignable to parameter with type `SupportsIndex` in function `tuple.__getitem__`",
	"source": "Pyre2",
	"startLineNumber": 1853,
	"startColumn": 45,
	"endLineNumber": 1853,
	"endColumn": 47,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "no-matching-overload",
	"severity": 8,
	"message": "Cannot index into `tuple[Unknown, ...]`\n  No matching overload found for function `tuple.__getitem__`, reporting errors for closest overload: `(SupportsIndex) -> Unknown`",
	"source": "Pyre2",
	"startLineNumber": 1857,
	"startColumn": 33,
	"endLineNumber": 1857,
	"endColumn": 55,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `slice[int, int, int]` is not assignable to parameter with type `SupportsIndex` in function `tuple.__getitem__`",
	"source": "Pyre2",
	"startLineNumber": 1857,
	"startColumn": 45,
	"endLineNumber": 1857,
	"endColumn": 54,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Generic attribute `from_seq` of class `PersistentVector` is not visible on the class",
	"source": "Pyre2",
	"startLineNumber": 1861,
	"startColumn": 16,
	"endLineNumber": 1861,
	"endColumn": 41,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Generic attribute `from_seq` of class `PersistentVector` is not visible on the class",
	"source": "Pyre2",
	"startLineNumber": 1865,
	"startColumn": 16,
	"endLineNumber": 1865,
	"endColumn": 41,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `int | None` is not assignable to declared return type `int`",
	"source": "Pyre2",
	"startLineNumber": 1915,
	"startColumn": 16,
	"endLineNumber": 1915,
	"endColumn": 26,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Item assignment is not supported on `dict[str, Error]`\n  Argument `int` is not assignable to parameter with type `str` in function `dict.__setitem__`",
	"source": "Pyre2",
	"startLineNumber": 2007,
	"startColumn": 22,
	"endLineNumber": 2007,
	"endColumn": 25,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Item assignment is not supported on `dict[str, Error]`\n  Argument `int` is not assignable to parameter with type `str` in function `dict.__setitem__`",
	"source": "Pyre2",
	"startLineNumber": 2014,
	"startColumn": 26,
	"endLineNumber": 2014,
	"endColumn": 29,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Item assignment is not supported on `dict[str, Error] | @8938`\n  Argument `int` is not assignable to parameter with type `str` in function `dict.__setitem__`",
	"source": "Pyre2",
	"startLineNumber": 2029,
	"startColumn": 26,
	"endLineNumber": 2029,
	"endColumn": 29,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Item assignment is not supported on `dict[str, Error]`\n  Argument `int` is not assignable to parameter with type `str` in function `dict.__setitem__`",
	"source": "Pyre2",
	"startLineNumber": 2056,
	"startColumn": 26,
	"endLineNumber": 2056,
	"endColumn": 29,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Item assignment is not supported on `dict[str, Error]`\n  Argument `int` is not assignable to parameter with type `str` in function `dict.__setitem__`",
	"source": "Pyre2",
	"startLineNumber": 2064,
	"startColumn": 26,
	"endLineNumber": 2064,
	"endColumn": 29,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `dict[str, Unknown]` is not assignable to declared return type `dict[?_TypeVar, ?_TypeVar]`",
	"source": "Pyre2",
	"startLineNumber": 2112,
	"startColumn": 16,
	"endLineNumber": 2112,
	"endColumn": 34,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "not-callable",
	"severity": 8,
	"message": "Expected a callable, got ((Any) -> ?_TypeVar) | None",
	"source": "Pyre2",
	"startLineNumber": 2131,
	"startColumn": 23,
	"endLineNumber": 2131,
	"endColumn": 34,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "not-callable",
	"severity": 8,
	"message": "Expected a callable, got None",
	"source": "Pyre2",
	"startLineNumber": 2131,
	"startColumn": 23,
	"endLineNumber": 2131,
	"endColumn": 34,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "not-callable",
	"severity": 8,
	"message": "Expected a callable, got ((Any) -> ?_TypeVar) | None",
	"source": "Pyre2",
	"startLineNumber": 2135,
	"startColumn": 25,
	"endLineNumber": 2135,
	"endColumn": 38,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "not-callable",
	"severity": 8,
	"message": "Expected a callable, got None",
	"source": "Pyre2",
	"startLineNumber": 2135,
	"startColumn": 25,
	"endLineNumber": 2135,
	"endColumn": 38,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `int | None` is not assignable to declared return type `int`",
	"source": "Pyre2",
	"startLineNumber": 2162,
	"startColumn": 16,
	"endLineNumber": 2162,
	"endColumn": 26,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Function declared to return `bool`, but one or more paths are missing an explicit `return`",
	"source": "Pyre2",
	"startLineNumber": 2187,
	"startColumn": 64,
	"endLineNumber": 2187,
	"endColumn": 68,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "`-` is not supported between `@9073` and `float`\n  Argument `None` is not assignable to parameter with type `float` in function `float.__rsub__`",
	"source": "Pyre2",
	"startLineNumber": 2214,
	"startColumn": 29,
	"endLineNumber": 2214,
	"endColumn": 51,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "no-matching-overload",
	"severity": 8,
	"message": "Cannot index into `list[Unknown]`\n  No matching overload found for function `list.__getitem__`, reporting errors for closest overload: `(SupportsIndex) -> Unknown`",
	"source": "Pyre2",
	"startLineNumber": 2240,
	"startColumn": 33,
	"endLineNumber": 2240,
	"endColumn": 42,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `slice[int, int, int]` is not assignable to parameter with type `SupportsIndex` in function `list.__getitem__`",
	"source": "Pyre2",
	"startLineNumber": 2240,
	"startColumn": 39,
	"endLineNumber": 2240,
	"endColumn": 41,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `object | Unknown` is not assignable to declared return type `?_TypeVar | None`",
	"source": "Pyre2",
	"startLineNumber": 2249,
	"startColumn": 24,
	"endLineNumber": 2249,
	"endColumn": 30,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `(?_TypeVar, Any) -> ?_TypeVar` is not assignable to parameter `fn` with type `(Unknown) -> Unknown` in function `Ref.alter`",
	"source": "Pyre2",
	"startLineNumber": 2327,
	"startColumn": 33,
	"endLineNumber": 2327,
	"endColumn": 35,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Class `STMAgent` has no class attribute `_agent_pool`",
	"source": "Pyre2",
	"startLineNumber": 2345,
	"startColumn": 21,
	"endLineNumber": 2345,
	"endColumn": 41,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Class `STMAgent` has no class attribute `_agent_pool`",
	"source": "Pyre2",
	"startLineNumber": 2349,
	"startColumn": 9,
	"endLineNumber": 2349,
	"endColumn": 29,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `Any | None` is not assignable to declared return type `?_TypeVar`",
	"source": "Pyre2",
	"startLineNumber": 2394,
	"startColumn": 16,
	"endLineNumber": 2394,
	"endColumn": 63,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Object of class `_local` has no attribute `value`",
	"source": "Pyre2",
	"startLineNumber": 2400,
	"startColumn": 9,
	"endLineNumber": 2400,
	"endColumn": 26,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Object of class `_local` has no attribute `value`",
	"source": "Pyre2",
	"startLineNumber": 2405,
	"startColumn": 17,
	"endLineNumber": 2405,
	"endColumn": 34,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Object of class `_local` has no attribute `tx`",
	"source": "Pyre2",
	"startLineNumber": 2428,
	"startColumn": 5,
	"endLineNumber": 2428,
	"endColumn": 19,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `None` is not assignable to declared return type `((...) -> Unknown) | ?_TypeVar`",
	"source": "Pyre2",
	"startLineNumber": 2532,
	"startColumn": 16,
	"endLineNumber": 2532,
	"endColumn": 29,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `_Wrapped[Ellipsis, ?_TypeVar, (*args: Unknown, **Unknown), ?_TypeVar]` is not assignable to declared return type `(...) -> ?_TypeVar`",
	"source": "Pyre2",
	"startLineNumber": 2621,
	"startColumn": 12,
	"endLineNumber": 2621,
	"endColumn": 19,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "no-matching-overload",
	"severity": 8,
	"message": "Cannot index into `list[tuple[VersionStamp, ?_TypeVar]]`\n  No matching overload found for function `list.__getitem__`, reporting errors for closest overload: `(SupportsIndex) -> tuple[VersionStamp, ?_TypeVar]`",
	"source": "Pyre2",
	"startLineNumber": 2650,
	"startColumn": 35,
	"endLineNumber": 2650,
	"endColumn": 56,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `slice[int, int, int]` is not assignable to parameter with type `SupportsIndex` in function `list.__getitem__`",
	"source": "Pyre2",
	"startLineNumber": 2650,
	"startColumn": 48,
	"endLineNumber": 2650,
	"endColumn": 55,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-return",
	"severity": 8,
	"message": "Returned type `tuple[int, None, Exception]` is not assignable to declared return type `tuple[int, ?_TypeVar, Exception | None]`",
	"source": "Pyre2",
	"startLineNumber": 2686,
	"startColumn": 20,
	"endLineNumber": 2686,
	"endColumn": 32,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `?_TypeVar` is not assignable to parameter with type `None` in function `list.__setitem__`",
	"source": "Pyre2",
	"startLineNumber": 2696,
	"startColumn": 13,
	"endLineNumber": 2696,
	"endColumn": 25,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "no-matching-overload",
	"severity": 8,
	"message": "Item assignment is not supported on `list[None] | @9200`\n  No matching overload found for function `list.__setitem__`, reporting errors for closest overload: `(SupportsIndex, None) -> None`",
	"source": "Pyre2",
	"startLineNumber": 2696,
	"startColumn": 13,
	"endLineNumber": 2696,
	"endColumn": 25,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Object of class `TransactionCoordinator` has no attribute `_reaper`",
	"source": "Pyre2",
	"startLineNumber": 2749,
	"startColumn": 9,
	"endLineNumber": 2749,
	"endColumn": 28,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Class `STMAgent` has no class attribute `_agent_pool`",
	"source": "Pyre2",
	"startLineNumber": 2751,
	"startColumn": 13,
	"endLineNumber": 2751,
	"endColumn": 33,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "bad-argument-type",
	"severity": 8,
	"message": "Argument `() -> None` is not assignable to parameter with type `(*Unknown, **Unknown) -> None` in function `atexit.register`",
	"source": "Pyre2",
	"startLineNumber": 2757,
	"startColumn": 17,
	"endLineNumber": 2757,
	"endColumn": 25,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/JimBras/Downloads/Atomix/Atomix.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "missing-attribute",
	"severity": 8,
	"message": "Generic attribute `from_seq` of class `PersistentVector` is not visible on the class",
	"source": "Pyre2",
	"startLineNumber": 2874,
	"startColumn": 10,
	"endLineNumber": 2874,
	"endColumn": 35,
	"origin": "extHost1"
}]''')

with open('Atomix.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

for err in errors:
    line_idx = err['startLineNumber'] - 1
    # Only add type: ignore if not already present
    if '# type: ignore' not in lines[line_idx]:
        lines[line_idx] = lines[line_idx].rstrip() + '  # type: ignore\n'

with open('Atomix.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)
